"""argparse definition for the trading simulator CLI."""
from __future__ import annotations

import argparse


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Trading Simulator with Algorithmic Traders")
    parser.add_argument("--mode", choices=["backtest", "live", "demo", "replay"], default="backtest", help="Run mode")
    parser.add_argument("--debug", action="store_true",
                        help="Show full Python tracebacks on expected/actionable errors instead of a clean one-line message")
    parser.add_argument("--symbol", default="AAPL", help="Ticker symbol")
    parser.add_argument("--start-date", default="2023-01-01", help="Backtest start date (YYYY-MM-DD)")
    parser.add_argument("--end-date", default="2023-12-31", help="Backtest end date (YYYY-MM-DD)")
    parser.add_argument("--fix-host", default="localhost", help="FIX server host")
    parser.add_argument("--fix-port", type=int, default=5005, help="FIX server port")
    parser.add_argument("--fix-sender-comp-id", default="SIMULATOR", help="FIX SenderCompID the server identifies itself as (tag 49)")
    parser.add_argument("--fix-target-comp-id", default="CLIENT", help="FIX TargetCompID the server expects clients to use (tag 56)")
    parser.add_argument("--fix-heartbeat-interval", type=int, default=30, help="FIX HeartBtInt in seconds (tag 108); also governs TestRequest/disconnect timeouts")
    parser.add_argument("--md-interval", type=int, default=60, help="Market data interval seconds")
    parser.add_argument("--symbols", default=None, help="Comma-separated symbols for multi-asset backtest")
    parser.add_argument("--enable-traders", action="store_true", help="Enable algorithmic traders")
    parser.add_argument("--sentiment-model-path", default="sentiment_classifier_model.keras", help="Sentiment model path")
    parser.add_argument("--news-api-key", default="", help="NewsAPI key for sentiment trader")
    parser.add_argument("--inject-liquidity", type=int, default=0, help="Inject synthetic liquidity every N seconds (0 disables)")
    parser.add_argument("--seed", type=int, default=None, help="Random seed for reproducibility")
    parser.add_argument("--sentiment-vocab-path", default=None, help="Vocabulary file for sentiment TextVectorization")
    parser.add_argument("--initial-cash", type=float, default=1_000_000.0, help="Initial portfolio cash")
    parser.add_argument("--fee-bps", type=float, default=0.0, help="Execution fee in basis points")
    parser.add_argument("--risk-max-order-qty", type=int, default=1000)
    parser.add_argument("--risk-max-symbol-position", type=int, default=10_000)
    parser.add_argument("--risk-max-gross-notional", type=float, default=5_000_000.0)
    parser.add_argument("--log-dir", default=".logs", help="Directory for CSV logs")
    parser.add_argument("--slippage-bps-per-100", type=float, default=0.0)
    parser.add_argument("--latency-ms", type=int, default=0)
    parser.add_argument("--export-report", action="store_true")
    parser.add_argument("--report-out", default="report.html")
    parser.add_argument("--optuna-trials", type=int, default=0)
    parser.add_argument("--mlflow-uri", default=None)
    parser.add_argument("--mlflow-experiment", default="trading-simulator")
    parser.add_argument("--order-cli-enable", action="store_true")
    parser.add_argument("--order-cli-host", default="127.0.0.1")
    parser.add_argument("--order-cli-port", type=int, default=8765)
    parser.add_argument("--order-cli-owner", default="cli")
    parser.add_argument("--replay-speed", type=float, default=1.0)
    parser.add_argument("--replay-interval-seconds", type=float, default=None)
    parser.add_argument("--momentum-lookback", type=int, default=5)
    parser.add_argument("--ema-short-window", type=int, default=5)
    parser.add_argument("--ema-long-window", type=int, default=20)
    parser.add_argument("--swing-support", type=float, default=100.0)
    parser.add_argument("--swing-resistance", type=float, default=200.0)
    parser.add_argument("--price-band-bps", type=float, default=0.0)
    parser.add_argument("--band-reference", choices=["mid", "last"], default="mid")
    parser.add_argument("--taker-fee-bps", type=float, default=0.0)
    parser.add_argument("--maker-rebate-bps", type=float, default=0.0)
    parser.add_argument("--use-queue", action="store_true")
    parser.add_argument("--queue-max", type=int, default=10000)
    parser.add_argument("--snapshot-interval-sec", type=int, default=0)
    parser.add_argument("--snapshot-dir", default=None)
    parser.add_argument("--risk-min-order-qty", type=int, default=1)
    parser.add_argument("--risk-lot-size", type=int, default=1)
    parser.add_argument("--risk-round-lot-required", action="store_true")
    parser.add_argument("--risk-order-rate-limit", type=int, default=None)
    parser.add_argument("--risk-owner-drawdown-limit", type=float, default=None)
    parser.add_argument("--risk-volatility-window", type=int, default=20)
    parser.add_argument("--risk-volatility-halt-z", type=float, default=None)
    parser.add_argument("--risk-max-leverage", type=float, default=None)
    parser.add_argument("--risk-max-symbol-gross-exposure", type=float, default=None)
    parser.add_argument("--custom-trader", action="append", default=[], help="module:ClassName (repeatable)")
    parser.add_argument("--custom-trader-params", action="append", default=[], help="JSON params, one per --custom-trader, same order")
    # Market maker parameters (Avellaneda-Stoikov quoting model). A market maker is
    # always constructed for backtest/replay/live modes, so these need defaults even
    # when the user never touches them via the guided CLI's "customize MM params" step.
    parser.add_argument("--mm-gamma", type=float, default=0.1, help="MM risk-aversion coefficient")
    parser.add_argument("--mm-k", type=float, default=1.5, help="MM order-book liquidity/decay parameter")
    parser.add_argument("--mm-horizon-seconds", type=float, default=60.0, help="MM quoting horizon in seconds")
    parser.add_argument("--mm-max-inventory", type=int, default=1000, help="MM max absolute inventory before skewing/halting quotes")
    parser.add_argument("--mm-base-order-size", type=int, default=100, help="MM base quote size per level")
    parser.add_argument("--mm-min-spread", type=float, default=0.01, help="MM minimum quoted spread")
    parser.add_argument("--mm-num-levels", type=int, default=2, help="MM number of quote levels per side")
    parser.add_argument("--mm-level-spacing-bps", type=float, default=2.0, help="MM spacing between quote levels, in bps")
    parser.add_argument("--mm-size-decay", type=float, default=0.7, help="MM per-level size decay factor (0-1]")
    parser.add_argument("--mm-momentum-window", type=int, default=10, help="MM momentum lookback window (ticks)")
    parser.add_argument("--mm-alpha-skew", type=float, default=0.5, help="MM quote skew sensitivity to momentum/inventory")
    parser.add_argument("--mm-vol-widen-z", type=float, default=2.0, help="MM spread-widening z-score threshold on volatility")
    parser.add_argument("--mm-drawdown-limit", type=float, default=0.2, help="MM kill-switch drawdown limit as a fraction of capital base")
    parser.add_argument("--mm-capital-base", type=float, default=100_000.0, help="MM capital base the drawdown kill-switch is measured against")
    return parser
